#!/bin/bash

# set -e
set -e

# Kinda self explanatory.
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
TARGET_DIR="$(dirname "$(readlink -f "$1")")"

# List everything
emudll32="$SCRIPT_DIR/uc/steam_api.dll"
targetdll32="$TARGET_DIR/steam_api.dll"
ogtarget32="$TARGET_DIR/steam_api_o.dll"
emudll64="$SCRIPT_DIR/uc/steam_api64.dll"
targetdll64="$TARGET_DIR/steam_api64.dll"
ogtarget64="$TARGET_DIR/steam_api64_o.dll"
blankshortcutmakerbat="$SCRIPT_DIR/uc/Template Make Desktop Shortcut Bat.bat"
genints32="$SCRIPT_DIR/uc/generate_interfaces_x32.exe"
genints64="$SCRIPT_DIR/uc/generate_interfaces_x64.exe"

# Check for target DLLs, there has to be a better way to do this
if [ -f "$targetdll32" ]; then
    mv "$targetdll32" "$ogtarget32"
    cp -f "$emudll32" "$targetdll32"
    wine "$genints32" "$ogtarget32"
    rm "$ogtarget32"
    cp -f "$blankshortcutmakerbat" "$TARGET_DIR/create_shortcut_on_desktop.bat"
    if [ -f "$targetdll64" ]; then
        mv "$targetdll64" "$ogtarget64"
        cp -f "$emudll64" "$targetdll64"
        wine "$genints64" "$ogtarget64"
        rm "$ogtarget64"
        cp -f "$blankshortcutmakerbat" "$TARGET_DIR/create_shortcut_on_desktop.bat"
    fi
else
    if [ -f "$targetdll64" ]; then
        mv "$targetdll64" "$ogtarget64"
        cp -f "$emudll64" "$targetdll64"
        wine "$genints64" "$ogtarget64"
        rm "$ogtarget64"
        cp -f "$blankshortcutmakerbat" "$TARGET_DIR/create_shortcut_on_desktop.bat"
    else
        echo "Error: no steam dlls of either kind found! If this is a mistake, contact vee.anti on discord or open an issue on the GitHub repo for this!"
        exit 1
    fi
fi

# Extra stuff

exit 0